version: 2.1
jobs:
  build:
    docker:
      - image: alpine/git:v2.26.2
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            pwd
            ls
            uname -a
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan -p 443 ssh.github.com > ~/.ssh/known_hosts
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git clone "${CIRCLE_REPOSITORY_URL}"
            ls
            printenv
            cd "${CIRCLE_PROJECT_REPONAME}"
            git branch
            git rev-parse HEAD
            git rev-parse --short HEAD
            echo "cb-${CIRCLE_BUILD_NUM}-$(git rev-parse --short HEAD)" > artifact.txt
            git add .
            git commit –am "[ci skip] build artifacts"
            git tag -a "cb-${CIRCLE_BUILD_NUM}-$(git rev-parse --short HEAD)" -m "[ci skip] tag with build artifacts"
            git branch
            git show "cb-${CIRCLE_BUILD_NUM}-$(git rev-parse --short HEAD)" 
            git push origin "cb-${CIRCLE_BUILD_NUM}-$(git rev-parse --short HEAD)"
